apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qih3r2i8t-nodejs-ci
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/qih3r2i8t-nodejs/overlays/ci
    repoURL: https://github.com/rhtap-rhdh-qe/qih3r2i8t-nodejs-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
