apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qih3r2i8t-nodejs
  janus-idp.io/tekton: qih3r2i8t-nodejs
  backstage.io/kubernetes-id: qih3r2i8t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qih3r2i8t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
