apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qih3r2i8t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qih3r2i8t-nodejs 
  name: qih3r2i8t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qih3r2i8t-nodejs 
